### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by lukakostic** [ebrian/blang#1]
Would be useful if you made some docs on how the language works and how to edit it. Like a simple guide of how it gets compiled / interpreted and what functionality does each class/header have

**Comment by realtux** [comment]
It's an abandoned project which really doesn't do much.

**Comment by lukakostic** [comment]
Right but i also want to make some sort of toy language (transpiled to c++, compiler written in c++) and i wanted to take a look how it all works. I already know basics of compilers (lexer,parser, action tree etc.) but wanted to see the code which isnt really commented much

**Comment by realtux** [comment]
You'll find what I've done to be a sub-optimal way of doing things. The intent of this project was actually to build some basic language function without actually researching the right way to do it. I would later compare what I did to the "right" way.
